apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "ibmcpcs.ibm.com/v1",
          "kind": "SecretShare",
          "metadata": {
            "name": "common-services"
          },
          "spec": {
            "configmapshares": [
              {
                "configmapname": "platform-auth-idp",
                "sharewith": [
                  {
                    "namespace": "kube-system"
                  }
                ]
              },
              {
                "configmapname": "oauth-client-map",
                "sharewith": [
                  {
                    "namespace": "services"
                  }
                ]
              },
              {
                "configmapname": "ibmcloud-cluster-info",
                "sharewith": [
                  {
                    "namespace": "kube-public"
                  }
                ]
              }
            ],
            "secretshares": [
              {
                "secretname": "icp-metering-api-secret",
                "sharewith": [
                  {
                    "namespace": "kube-system"
                  }
                ]
              },
              {
                "secretname": "oauth-client-secret",
                "sharewith": [
                  {
                    "namespace": "services"
                  }
                ]
              },
              {
                "secretname": "ibmcloud-cluster-ca-cert",
                "sharewith": [
                  {
                    "namespace": "kube-public"
                  }
                ]
              },
              {
                "secretname": "icp-serviceid-apikey-secret",
                "sharewith": [
                  {
                    "namespace": "kube-system"
                  }
                ]
              },
              {
                "secretname": "platform-oidc-credentials",
                "sharewith": [
                  {
                    "namespace": "kube-system"
                  }
                ]
              },
              {
                "secretname": "icp-mongodb-admin",
                "sharewith": [
                  {
                    "namespace": "kube-system"
                  }
                ]
              },
              {
                "secretname": "icp-mongodb-client-cert",
                "sharewith": [
                  {
                    "namespace": "kube-system"
                  }
                ]
              },
              {
                "secretname": "cs-ca-certificate-secret",
                "sharewith": [
                  {
                    "namespace": "kube-system"
                  }
                ]
              }
            ]
          }
        }
      ]
    capabilities: Basic Install
  name: ibm-secretshare-operator.v1.2.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: SecretShare is the Schema for the secretshares API
      kind: SecretShare
      name: secretshares.ibmcpcs.ibm.com
      specDescriptors:
      - description: Configmapshares defines a list of configmap sharing information
        displayName: Configmapshares
        path: configmapshares
      - description: Secretshares defines a list of secret sharing information
        displayName: Secretshares
        path: secretshares
      version: v1
  description: Placeholder description
  displayName: Ibm Secretshare Operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - namespaces
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - secretshare
          resources:
          - deployments/finalizers
          verbs:
          - update
          - get
          - list
          - watch
        - apiGroups:
          - ibmcpcs.ibm.com
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: secretshare
      deployments:
      - name: secretshare
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: secretshare
          strategy: {}
          template:
            metadata:
              labels:
                name: secretshare
            spec:
              containers:
              - command:
                - secretshare
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: secretshare
                image: quay.io/opencloudio/ibm-secretshare-operator:v1.2
                imagePullPolicy: Always
                name: secretshare
                resources: {}
              serviceAccountName: secretshare
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  replaces: ibm-secretshare-operator.v0.0.0
  version: 1.2.0
