kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secretshare
subjects:
- kind: ServiceAccount
  name: secretshare
  namespace: ibm-common-services
roleRef:
  kind: ClusterRole
  name: secretshare
  apiGroup: rbac.authorization.k8s.io
